import { SIMULATION_VERSION } from './contracts/simulation-version.js'

export const version = SIMULATION_VERSION

export {
  BUILDING_DEFINITIONS,
  UNIT_DEFINITIONS,
  unitCanAttack,
  unitDefinitionFor
} from '@rts/game-data'
export type { RngState } from '@rts/shared'
export * from './canonical/resource-codecs.js'
export * from './commands/limits.js'
export * from './contracts/commands.js'
export * from './contracts/orders.js'
export * from './contracts/rules-identity.js'
export * from './contracts/simulation.js'
export * from './data/economy-rules.js'
export * from './data/production-rules.js'
export * from './data/supply-rules.js'
export * from './domain/building-predicates.js'
export * from './domain/formation.js'
export * from './domain/research-effects.js'
export * from './domain/tier-access.js'
export * from './ecs/building-component.js'
export * from './ecs/component-store.js'
export * from './ecs/components.js'
export * from './ecs/create-unit.js'
export * from './ecs/create-world.js'
export * from './ecs/remove-entity.js'
export * from './ecs/world.js'
export * from './engine/create-simulation.js'
export * from './engine/observation.js'
export * from './engine/simulation-from-snapshot.js'
export * from './engine/simulation-host.js'
export * from './invariants/check-invariants.js'
export * from './movement/destination.js'
export * from './orders/order-queue.js'
export * from './placement/index.js'
export * from './resources/resource-catalog.js'
export * from './resources/resource-spatial-index.js'
export * from './resources/resource-state.js'
export * from './snapshot/hash.js'
export * from './snapshot/serialize.js'
export * from './state/state.js'
export * from './systems/events.js'
export * from './systems/heal-system.js'
export * from './systems/movement-step.js'
export * from './systems/pipeline.js'
export * from './systems/production-system.js'
export * from './systems/supply-system.js'
export * from './systems/tier-system.js'
