import { SIMULATION_VERSION } from './contracts/simulation-version.js'

export const version = SIMULATION_VERSION

export { BUILDING_DEFINITIONS } from '@rts/game-data'
export type { RngState } from '@rts/shared'
export * from './commands/limits.js'
export * from './contracts/commands.js'
export * from './contracts/orders.js'
export * from './contracts/rules-identity.js'
export * from './contracts/simulation.js'
export * from './data/economy-rules.js'
export * from './data/supply-rules.js'
export * from './data/unit-stats.js'
export * from './domain/building-predicates.js'
export * from './ecs/building-component.js'
export * from './ecs/component-store.js'
export * from './ecs/components.js'
export * from './ecs/create-world.js'
export * from './ecs/world.js'
export * from './engine/create-simulation.js'
export * from './engine/simulation-from-snapshot.js'
export * from './engine/simulation-host.js'
export * from './formation.js'
export * from './invariants/check-invariants.js'
export * from './movement/destination.js'
export * from './orders/order-queue.js'
export * from './placement/index.js'
export * from './snapshot/hash.js'
export * from './snapshot/serialize.js'
export * from './state/state.js'
export * from './systems/events.js'
export * from './systems/pipeline.js'
export * from './systems/supply-system.js'
