import type { PostmortemStatusData } from './postmortem-status-data.js'

export function renderPostmortemStatus(data: PostmortemStatusData, updatedOn: string): string {
  const lines: string[] = [
    '# Postmortem Status',
    '',
    '> Automatically generated by `tools/quality/postmortem-status.ts`',
    `> Updated: ${updatedOn}`,
    '',
    '## Summary',
    '',
    '| Status | Quantidade |',
    '|--------|------------|',
    `| open | ${data.openCount} |`,
    `| closed | ${data.closedCount} |`,
    `| **total** | **${data.entries.length}** |`,
    '',
    '## Details',
    '',
    '| Postmortem | Status | Class | Barrier | Regression |',
    '|------------|--------|-------|---------|------------|'
  ]

  for (const { name, frontMatter } of data.entries) {
    const statusIcon = frontMatter.status === 'closed' ? 'closed' : 'open'
    const barrier = frontMatter.barreira ?? '—'
    const regression = frontMatter.regressao.length > 0 ? `${frontMatter.regressao.length} test(s)` : 'none'
    lines.push(`| ${name} | ${statusIcon} | ${frontMatter.classe} | ${barrier} | ${regression} |`)
  }

  lines.push('')
  lines.push('## Legend')
  lines.push('')
  lines.push('- **open** = bug fixed, but it may happen again (no class barrier)')
  lines.push('- **closed** = bug fixed AND a class barrier exists (does not return)')
  lines.push('- **Barrier** = the quality gate that provides the class barrier')
  lines.push('- **Regression** = permanent test(s) that validate the fix')
  lines.push('')

  return lines.join('\n')
}
